name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3

      - name: Setup Node ðŸŒ±
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install â¬‡ï¸
        run: cd client && npm ci 
      
      - name: Build ðŸ—ï¸
        run: cd client && CI=false npm run build

      - name: Create .env ðŸ“
        run: |
          touch client/.env
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > client/.env

      - name: Deploy to Firebase ðŸš€
        uses: w9jds/firebase-action@v11.18.0  
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./client